<?php

/**
 * @file
 * Contains aqua_migrate.module.
 */
use Drupal\Core\Form\FormStateInterface;

function aqua_migrate_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $current_path = \Drupal::service('path.current')->getPath();
  if($current_path == '/admin/structure/migrate/manage/migrate_directory_nodes/migrations/import_node_events_xml/execute') {
    if($form_id == "migration_execute_form") {
      $form['operations']['options']['update']['#default_value'] = TRUE;
    }
  }
}
